# Generated by Django 3.0.3 on 2020-03-05 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200201_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='program',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='year_of_study',
        ),
    ]
